### ISSUE TITLE
How does it relate to others backport libraries like "aiocontextvars"?

### ISSUE THREAD

**Issue by Delgan** [itsVale/better-contextvars#1]
Hi. :)

While looking for a Python 3.5 backport of PEP 567, I come across your `better-contextvars` library but also the [`aiocontextvars`](https://github.com/fantix/aiocontextvars) (which itself relies on the [`contextvars`](https://github.com/MagicStack/contextvars) backport).

Basically, I would like to know if there is any difference between your library and others ones? Did you decide to go with your own because you noticed problems in the alternative implementations?

**Comment by vbe0201** [comment]
Hello Delgan, from what I can tell, there isn't much difference. I was writing this to get myself a better understanding of how the `contextvars` module works internally and to challenge myself as I had no experience with context variables and it wasn't really a pleasure to read its original source code.

Since all of these modules are striving for similar functionality, they should be fairly similar. From a neutral viewpoint, it shouldn't matter which implementation you choose in the end.

**Comment by Delgan** [comment]
Thanks for the clarification! Looking at the source code, your two libraries are very similar, so it should not make much difference as you said. Just wanted to be sure. Thanks. :+1:
